### PR TITLE
Fixed bugs, translation and info Improvements, add netherite hammer

### LINKED ISSUE #37: Hammer "silktouches" blocks
**Describe the bug**
Using the hammer on a block that isn't in the HammerRegistry gives a silktouched version. Such as coal ore doesn't drop coal, grass blacks don't drop coal.

**To Reproduce**
Pretty much says it up top.

**Expected behavior**
Expect it to act like an open hand or pickaxe without silk touch.

**Screenshots**

**Version**
Minecraft Version: 1.16.3
Forge Version: 34.1.23
Ex Nihilo: Sequentia Version: 1.16-1.2.1.2.jar

**Additional context**
I have a hunch thinking it may have something to do with the loot table only accepting blocks and not items. Not sure though because that doesn't explain grass not droping dirt. Either way it would be a nice QoL addition to be able to get items from hammering blocks like previous versions of Ex Nihilo.

### PR DESCRIPTION
**Pull request by yzl210**
1. Fixed a bug that can put more than 1000 solid into a crucible
2. translation and info improved:
Crucible:
image
image

Barrel:
image
image
3.Mesh type info localization:
image
image
4.Add netherite hammer:
image
5.Fix Sieve can block vision and suffocate players
6.Fix hammer drop the original block(silk touch) when the block is not hammerable(fix #37)

### CODE REVIEW

**Comment by Blackout03** [comment]
You should make the title reflect what is added instead of just calling it "improvements"
something like "Fixed bugs, Improved translations and Added Netherite Hammer"

**Comment by NovaMachina** [comment]
I will review this as soon as I get the current feature I'm working done on.

File: src/main/java/com/novamachina/exnihilosequentia/common/block/BlockSieve.java [hunk 1]
```diff
@@ -7,14 +7,12 @@
...
+import com.novamachina.exnihilosequentia.common.utility.Constants;
 import com.novamachina.exnihilosequentia.common.utility.StringUtils;
 import mcjty.theoneprobe.api.IProbeHitData;
 import mcjty.theoneprobe.api.IProbeInfo;
 import mcjty.theoneprobe.api.ProbeMode;
-import net.minecraft.block.Block;
-import net.minecraft.block.BlockState;
-import net.minecraft.block.IWaterLoggable;
-import net.minecraft.block.SoundType;
+import net.minecraft.block.*;
```
Comment (NovaMachina) [inline src/main/java/com/novamachina/exnihilosequentia/common/block/BlockSieve.java]: No bulk imports.

Since you have made this pull request I have added contributing guidelines.

File: src/main/java/com/novamachina/exnihilosequentia/common/datagen/Recipes.java [hunk 2]
```diff
@@ -27,12 +27,7 @@
 import net.minecraft.advancements.criterion.InventoryChangeTrigger;
 import net.minecraft.block.Block;
 import net.minecraft.block.Blocks;
-import net.minecraft.data.CookingRecipeBuilder;
-import net.minecraft.data.DataGenerator;
-import net.minecraft.data.IFinishedRecipe;
-import net.minecraft.data.RecipeProvider;
-import net.minecraft.data.ShapedRecipeBuilder;
-import net.minecraft.data.ShapelessRecipeBuilder;
+import net.minecraft.data.*;
```
Comment (NovaMachina) [inline src/main/java/com/novamachina/exnihilosequentia/common/datagen/Recipes.java]: No bulk imports.

Since you have made this pull request I have added contributing guidelines.

File: src/main/java/com/novamachina/exnihilosequentia/common/tileentity/crucible/MeltableItemHandler.java [hunk 3]
```diff
@@ -11,17 +11,20 @@
...
         type = crucibleType;
+        this.crucibleTile = crucibleTile;
     }
 
     @Nonnull
     @Override
     public ItemStack insertItem(int slot, @Nonnull ItemStack stack, boolean simulate) {
-        if (crucibleHasRoom) {
+        int amount = ExNihiloRegistries.CRUCIBLE_REGISTRY.getMeltable(stack.getItem()).getAmount();
+        if (crucibleHasRoom && crucibleTile.getSolidAmount() <= 1000 - amount * stack.getCount()) {
```
Comment (NovaMachina) [inline src/main/java/com/novamachina/exnihilosequentia/common/tileentity/crucible/MeltableItemHandler.java]: The solid amount can be variable and set by a config. Having a hardcoded 1000 disrupts this.

**Review by NovaMachina — CHANGES_REQUESTED** [review]

**Review by NovaMachina — APPROVED** [review]
